=== Uintah/Uintah/kokkos_dev/teem_tuple_removed/src/Packages/Insight/ITK/itk_filter.dtd
<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->

<!ELEMENT filter-itk (description, templated, datatypes?, inputs?, outputs?, parameters?, includes)>
  <!ATTLIST filter-itk name CDATA #REQUIRED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT templated (template*, defaults*)>

<!ELEMENT template (#PCDATA)>
  <!ATTLIST template type CDATA #IMPLIED>

<!ELEMENT defaults (default*)>

<!ELEMENT default (#PCDATA)>

<!ELEMENT datatypes (array+)>

<!ELEMENT array (elem-type, size-call)>
  <!ATTLIST array name CDATA #REQUIRED>

<!ELEMENT elem-type (#PCDATA)>

<!ELEMENT size-call (#PCDATA)>
 
<!ELEMENT inputs (input*)>

<!ELEMENT input (type, call)>
  <!ATTLIST input name CDATA #REQUIRED>
  <!ATTLIST input optional (yes|no) "no">

<!ELEMENT call (#PCDATA)>
  <!ATTLIST call const (yes|no) "no">
  <!ATTLIST call value (on|off) "off">

<!ELEMENT name (#PCDATA)>

<!ELEMENT outputs (output*)>

<!ELEMENT output (type, call)>
  <!ATTLIST output name CDATA #REQUIRED>

<!ELEMENT parameters (param*)>

<!ELEMENT param (name, type, ((call, call) | call), default?)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT includes (file*)>

<!ELEMENT file (#PCDATA)>

=== Uintah/Uintah/kokkos_dev/teem_tuple_removed/src/Packages/Insight/ITK/itk_UnaryFunctorImageFilter.xml
<?xml version="1.0"?>
<!DOCTYPE filter-itk SYSTEM "itk_filter.dtd">

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->

<filter-itk name="itk::UnaryFunctorImageFilter">
  <description>
Implements pixel-wise generic operation on one image.
  </description>
  <templated>
    <template>InputImageType</template>
    <template>OutputImageType</template>
    <template>FunctionType</template>
    <defaults>
      <default>itk::Image&lt;unsigned long, 3&gt;</default>
      <default>itk::Image&lt;itk::RGBPixel&lt;unsigned char&gt;, 3&gt;</default>
      <default>itk::Functor::ScalarToRGBPixelFunctor&lt;unsigned long&gt;</default>
    </defaults>
    <defaults>
      <default>itk::Image&lt;unsigned long, 2&gt;</default>
      <default>itk::Image&lt;itk::RGBPixel&lt;unsigned char&gt;, 2&gt;</default>
      <default>itk::Functor::ScalarToRGBPixelFunctor&lt;unsigned long&gt;</default>
    </defaults>
  </templated>

  <inputs>
    <input name="InputImage">
      <type>InputImageType</type>
      <call>SetInput</call>
    </input>  
  </inputs>
  <outputs>
    <output name="OutputImage">
      <type>OutputImageType</type>
      <call>GetOutput</call>
    </output>
  </outputs>

  <parameters>
  </parameters>

  <includes>
    <file>itkUnaryFunctorImageFilter.h</file>
    <file>itkRGBPixel.h</file>
    <file>itkScalarToRGBPixelFunctor.h</file>
  </includes>
</filter-itk>
