=== Uintah/Uintah/kokkos_dev/virtual/SCIRun/src/Dataflow/XML/component.dtd
<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->


<!-- ********** Parameter Entities ********** -->

<!ENTITY % filename "(#PCDATA)">

<!-- links -->
<!-- Links may contain phrases but not vice-versa -->
<!ENTITY % links "rlink | slink | ulink |  modref | xref | email | cite">

<!-- "Phrases" -->
<!ENTITY % phrase "firstterm | keyword | userinput | abbr | latex | path | emph | quote">
<!ENTITY % phrase.content "(#PCDATA)">

<!-- Inlines -->
<!ENTITY % inline "%phrase; | %links;">
<!ENTITY % Inline "(#PCDATA | %inline;)*">
<!ENTITY % link.content "(#PCDATA | %phrase;)*">

<!-- Block level -->
<!ENTITY % list "orderedlist | unorderedlist | desclist">
<!ENTITY % admonition "note | tip | warning">
<!ENTITY % block "p | latex | figure | pre">

<!-- "Flow" level -->
<!ENTITY % BasicFlow "(%block; | %list;)*">
<!ENTITY % DescFlow "(section | developer | %block; | %list; | %admonition;)*">
<!ENTITY % DevFlow "(%block; | %list; | %admonition;)*">
<!ENTITY % AdmonFlow "(%block; | %list;)*">

<!-- ********** Elements ********** -->

<!-- A couple of reusable elements  -->
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT componentname (#PCDATA)>
<!ELEMENT devicename (#PCDATA)>
<!ELEMENT title %Inline;>

<!-- Top level -->
<!ELEMENT component (overview, io, gui?, nets?, testing?)>
<!ATTLIST component 
        name CDATA #REQUIRED
        category CDATA #REQUIRED
        optional (true | false) "false"
				hide (true | false) "false">

<!--  Overview of component's purpose  -->
<!ELEMENT overview (authors, summary)>

<!-- Brief (1 or 2 sentence) summary. -->
<!ELEMENT summary %Inline;>

<!--  Author(s) -->
<!ELEMENT authors (author+)>

<!--  1 author  -->
<!ELEMENT author %Inline;>

<!-- Net descriptions -->
<!ELEMENT nets (net+)>
<!ELEMENT net (title, %DescFlow;)>
<!ATTLIST net id CDATA #REQUIRED>

<!-- Component's inputs and outputs  -->
<!ELEMENT io (inputs, outputs?)>

<!-- Component's inputs.  Inputs may come from a file, port, or device.  -->
<!ELEMENT inputs (port*)>
<!ATTLIST inputs lastportdynamic (yes | no) "no">

<!-- Component's outputs.  Outputs may be sent to a file, port, or device. -->
<!ELEMENT outputs (port*)>

<!-- Describe data on port (i.e. temperature data) and the datatype being
     transmitted.  --> 
<!ELEMENT port (name, description?, datatype, componentname*)>

<!-- The user-defined name for this port -->
<!ELEMENT name (#PCDATA)>

<!-- GUI description (words and pictures) -->
<!-- Note: '(img, caption?)*' part of content model is obsolete. Use -->
<!-- figure and figref elements within a description element instead. -->
<!ELEMENT gui (description?, parameter*, (img, caption?)*)>

<!-- Description of 1 gui parameter. -->
<!ELEMENT parameter (widget, label, description)>

<!-- Name of gui widget (e.g. slider, text entry, checkbox)-->
<!ELEMENT widget (#PCDATA)>

<!-- Gui item label -->
<!ELEMENT label (#PCDATA)>

<!--  Name of an image file -->
<!ELEMENT img %filename;>

<!-- Image caption -->
<!ELEMENT caption %Inline;>

<!-- Specify testing plan(s) -->
<!ELEMENT testing (plan+)>

<!-- Specify 1 testing plan.  -->
<!ELEMENT plan (description, step+)>

<!-- Specify 1 testing step -->
<!ELEMENT  step %DescFlow;>

<!-- Mini-documentation environment -->
<!ELEMENT description %DescFlow;>
<!ATTLIST description id ID #IMPLIED>

<!-- Description, net, and section subdivision -->
<!ELEMENT section (title?, %DescFlow;)>
<!ATTLIST section id ID #IMPLIED>

<!-- Description information targeted at developers -->
<!ELEMENT developer %DevFlow;>

<!-- Calls attention to some piece of information. -->
<!ELEMENT note %AdmonFlow;>

<!-- A friendly word of advice. --> 
<!ELEMENT tip %AdmonFlow;>

<!-- A warning of some sort. -->
<!ELEMENT warning %AdmonFlow;>

<!-- Paragraph. -->
<!ELEMENT p %Inline;>

<!--  Inline elements -->
<!ELEMENT firstterm %phrase.content;>   <!-- Introduce a new term -->
<!ELEMENT keyword %phrase.content;>     <!-- Introduce a keyword -->
<!ELEMENT userinput %phrase.content;>   <!-- Something entered by the user -->
<!ELEMENT cite %phrase.content;>        <!-- Citation -->
<!ATTLIST cite           
        url CDATA #IMPLIED>
<!ELEMENT abbr %phrase.content;>        <!-- An abbreviation -->          
<!ELEMENT path %phrase.content;>        <!-- Path to file or directory -->
<!ELEMENT emph %phrase.content;>        <!-- Emphasized text -->
<!ELEMENT quote %phrase.content;>       <!-- Quoted text -->
<!ELEMENT email %phrase.content;>       <!-- Email address with link text -->
<!ATTLIST email
        addr CDATA #REQUIRED>
<!ELEMENT xref %phrase.content;>        <!-- General reference -->
<!ATTLIST xref
        target IDREF #REQUIRED>
<!ELEMENT modref %phrase.content;>      <!-- Module reference -->
<!ATTLIST modref
        package NMTOKEN #REQUIRED
        name CDATA #REQUIRED>
<!ELEMENT rlink %link.content;>         <!-- Link from root of CVS tree -->
<!ATTLIST rlink
        path CDATA #REQUIRED>
<!ELEMENT slink %link.content;>         <!-- Link into SCI web site -->
<!ATTLIST slink
        path CDATA #REQUIRED>
<!ELEMENT ulink %link.content;>         <!-- URL link -->
<!ATTLIST ulink
        url CDATA #REQUIRED>

<!-- Ordered list, unordered list, and description list. -->
<!ELEMENT orderedlist (listitem)+>
<!ELEMENT unorderedlist (listitem)+>
<!ELEMENT listitem %BasicFlow;>
<!ELEMENT desclist (desclistitem)+>
<!ELEMENT desclistitem (desclistterm, desclistdef)>
<!ELEMENT desclistterm (#PCDATA)>
<!ELEMENT desclistdef %BasicFlow;>

<!-- Latex element.  Acts as both an inline phrase type element and a
     block element --> 
<!ELEMENT latex (#PCDATA)>

<!-- Figure element -->
<!ELEMENT figure (img, caption)>
<!ATTLIST figure id ID #IMPLIED>

<!-- Pre element -->
<!ELEMENT pre (#PCDATA)>

=== Uintah/Uintah/kokkos_dev/virtual/SCIRun/src/Packages/ModelCreation/Dataflow/XML/MapFieldDataGradientOntoField.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<component name="MapFieldDataGradientOntoField" category="ChangeFieldData" optional="false">
  <overview>
    <authors>
      <author>Jeroen Stinstra</author>
    </authors>
    <summary>
      This module maps the gradient on the destination field.

    </summary>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Source</name>
        <datatype>SCIRun::Field</datatype>
      </port>
      <port>
        <name>Destination</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>Destination</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
</component>

=== Uintah/Uintah/kokkos_dev/virtual/SCIRun/src/Packages/ModelCreation/Dataflow/XML/ConvertMeshToPointCloud.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<component name="ConvertMeshToPointCloud" category="ChangeMesh">
  <overview>
    <authors>
      <author>Jeroen Stinstra</author>
    </authors>
    <summary>
      Convert a field into a PointCloud field.
    </summary>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Field</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>Field</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
</component>

=== Uintah/Uintah/kokkos_dev/virtual/SCIRun/src/Dataflow/XML/BuildMatrixOfSurfaceNormals.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "component.dtd">
<?xml-stylesheet href="component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->



<component name="BuildMatrixOfSurfaceNormals" category="MiscField">
  <overview>
    <authors>
      <author>Martin Cole</author>
    </authors>
    <summary>The BuildMatrixOfSurfaceNormals calculates area weighted normal Vectors per node.</summary>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <!-- one of (device port file) -->
      <port>
	<name>Surface Field</name>
	<description>
	  <p>
             Accepts only surface fields.
          </p>
	</description>
	<datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <!-- one of (device port file) -->
      <port>
	<name>Nodal Surface Normals</name>
	<description>
	  <p>DenseMatrix of Vectors, one per node in input.</p>
	</description>
	<datatype>SCIRun::Matrix</datatype>
      </port>
    </outputs>
  </io>
 </component>

=== Uintah/Uintah/kokkos_dev/virtual/SCIRun/src/Packages/ModelCreation/Dataflow/XML/MapCurrentDensityOntoField.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<component name="MapCurrentDensityOntoField" category="ChangeFieldData" optional="false">
  <overview>
    <authors>
      <author>Jeroen Stinstra</author>
    </authors>
    <summary>
      This module maps potentials and conductivities into a current density field. The module samples the underlying fields and averages or integrates the data and puts the result on the elements of the output mesh. The module has the option to do the dot product with the current density field as well for surface destination meshes.

    </summary>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Potential</name>
        <datatype>SCIRun::Field</datatype>
      </port>
      <port>
        <name>Conductivity</name>
        <datatype>SCIRun::Field</datatype>
      </port>
      <port>
        <name>Destination</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>Destination</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
</component>

=== Uintah/Uintah/kokkos_dev/virtual/SCIRun/src/Packages/BioPSE/Dataflow/XML/ApplyFEMCurrentSource.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<?xml-stylesheet href="../../../../Dataflow/XML/component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->



<component name="ApplyFEMCurrentSource" category="Forward">
  <overview>
    <authors>
      <author>David Weinstein</author>
    </authors>
    <summary>The ApplyFEMCurrentSource module builds the right-hand
side (ColumnMatrix) to reflect monopolar and dipolar current sources
for finite-element based bioelectric field problems.</summary>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <!-- one of (device port file) -->
      <port>
	<name>Mesh</name>
	<description>
	  <p>Field containing the volume mesh</p>
	</description>
	<datatype>SCIRun::Field</datatype>
	<componentname>FieldReader</componentname>
      </port>
      <port>
	<name>Sources</name>
	<description>
	  <p>Either a PointCloudField&lt;Vector> (for dipoles) or a
PointCloudField&lt;double> for current densities.</p>
	</description>
	<datatype>SCIRun::Field</datatype>
	<componentname>FieldReader</componentname>
      </port>
      <port>
	<name>Mapping</name>
	<description>
	  <p>Maps source nodes indicies to volume mesh nodes
indices.</p>
	</description>
	<datatype>SCIRun::Matrix</datatype>
	<componentname>MatrixReader</componentname>
      </port>
      <port>
	<name>Input RHS</name>
	<description>
	  <p>(Optional) Handle to the matrix containing RHS for FE
discretization obtained from SetupFEMatrix.</p>
	</description>
	<datatype>SCIRun::Matrix</datatype>
	<componentname>SetupFEMatrix</componentname>
	<componentname>MatrixReader</componentname>
      </port>
    </inputs>

    <outputs>
      <!-- one of (device port file) -->
      <port>
	<name>Output RHS</name>
	<description>
	  <p>Sends handle to Matrix containing dipole terms to
downstream modules</p>
	</description>
	<datatype>SCIRun::Matrix</datatype>
	<componentname>SolveMatrix</componentname>
	<componentname>MatrixWriter</componentname>
      </port>
      <port>
        <name>Output Weights</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
    </outputs>
  </io>
</component>

=== Uintah/Uintah/kokkos_dev/virtual/SCIRun/src/Packages/BioPSE/Dataflow/XML/SimulateDipoleInAnisoSpheresAnalytically.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->



<component name="SimulateDipoleInAnisoSpheresAnalytically" category="Forward">
  <overview>

    <authors>
      <author>Sascha Moehrs</author>
    </authors>

    <summary>
Due to a specified dipole, the potential on the outer sphere of a four
layer spherical volume conductor is computed.
</summary>


  </overview>

  <io>

    <inputs lastportdynamic="no">
      <port>
	<name>Electrodes</name>
	<description>
	  <p>The port takes a handle of the electrode positions where
the potential has to be computed.</p>
	</description>
	<datatype>SCIRun::Field</datatype>
      </port>
      <port>
	<name>Dipole Sources</name>
	<description>
	  <p>The port takes a handle to the matrix that is 1-by-6 in
size, containing parameters of 1 dipole.  The first three columns are
dipole position. The last three colums are dipole moments. If the
dipole lies outside the innermost sphere, the log window creates a
warning message.</p>
	</description> 
	<datatype>SCIRun::Field</datatype>
      </port>

      <port>
	<name>Radii</name>
	<description>
	  <p>The port takes a matrix containing the radii for scalp,
skull, cerebrospinal fluid and the brain.</p>
	</description>
	<datatype>SCIRun::Matrix</datatype>
      </port>

      <port>
	<name>AnisoConductivities</name>
	<description>
	  <p>The port takes a matrix containing radial and tangential
conductivities of all 4 layers.</p>
	</description>
	<datatype>SCIRun::Matrix</datatype>
      </port>
    </inputs>

    <outputs>

      <port>
	<name>ElectrodePotentials</name>
	<description>
	  <p>The initial field is populated with potential values.</p>
	</description>
	<datatype>SCIRun::Field</datatype>
      </port>

    </outputs>

  </io>

  <gui> 
    <description>
    </description>
    <parameter>
      <widget>Text Entry</widget>
      <label></label>
      <description>
      </description>
    </parameter>
    <parameter>
      <widget>Text Entry</widget>
      <label>Expansion Terms</label>
      <description>
      </description>
    </parameter>
  </gui>

  <nets>
    <net id="new.das">
      <title>Dipole In Anisotropic Spheres</title>

      <p>Use of module SimulateDipoleInAnisoSpheresAnalytically is shown in <xref
target="fig.das"/>.  The network computes potentials on the surface of
a sphere.</p>

      <figure id="fig.das">
	<img>../Modules/Forward/doc/sphere.gif</img> 
	<caption>Anisotropic Sphere Model Network</caption>
      </figure>

      <section>
	<title>Inputs</title> 

	<p>SimulateDipoleInAnisoSpheresAnalytically receives sphere model parameters from
module <modref package="BioPSE" name="AnisoSphereModel"/>.  Electrode
positions are recieved, as a field, on the first yellow port. Sphere
radii parameters are recieved, as a matrix, on the first blue port.
Conductivity data are recieved, as a matrix, on the second blue
port.</p> 

	<p>Dipole field data are recieved on the second yellow port
from module <modref package="BioPSE" name="ShowDipoles"/>.</p>

      </section>

      <section>
	<title>Outputs</title>

	<p>SimulateDipoleInAnisoSpheresAnalytically generate  a potential field (electrode
positions and corresponding potential values, which is then
transmitted on its sole output port to modules <modref
package="SCIRun" name="ShowField"/> and <modref package="SCIRun"
name="RescaleColorMap"/>.</p> 

	<p>The potential field and dipole are rendered by module
<modref package="SCIRun" name="Viewer"/> from scene graph data
produced by modules <modref package="SCIRun" name="ShowField"/> and
<modref package="BioPSE" name="ShowDipoles"/>.</p>
      </section>

    </net>
  </nets>
</component>
