=== Uintah/Uintah/kokkos_dev/FIELD_REDESIGN/doc/ReferenceGuide/component.dtd
<!--
        
Component  specification dtd.

-->

<!-- ********** Parameter Entities ********** -->

<!ENTITY % filename "(#PCDATA)">

<!-- A relative path specification. Used by rlink and slink elements'
     attributes. --> 
<!ENTITY % rpath "CDATA">

<!-- Link stuff -->
<!ENTITY % links "rlink | slink">
<!ENTITY % rlink.attr "path %rpath; #REQUIRED">

<!-- Text level stuff -->
<!ENTITY % phrase "term | keyword | keyboard | cite | acronym">
<!ENTITY % phrase.content "(#PCDATA)">
<!ENTITY % inline "%phrase; | %links;">
<!ENTITY % Inline "(#PCDATA | %inline;)*">
<!ENTITY % link.content "(#PCDATA | %phrase;)*">

<!-- Higher level stuff -->
<!ENTITY % lists "orderedlist | unorderedlist | desclist">
<!ENTITY % admonition "note | tip | warning">
<!ENTITY % block "p">
<!ENTITY % flow "%block; | %lists;">
<!ENTITY % BasicFlow "(%flow;)*">
<!ENTITY % DescFlow "(%flow; | developer | %admonition;)*">
<!ENTITY % DevFlow "(%flow; | %admonition;)*">
<!ENTITY % AdmonFlow "(%flow;)*">

<!-- ********** Elements ********** -->

<!-- A couple of reusable elements  -->
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT componentname (#PCDATA)>
<!ELEMENT devicename (#PCDATA)>

<!-- Top level -->
<!ELEMENT component (overview, implementation?, io, gui?, testing)>
<!ATTLIST component 
        name CDATA #REQUIRED
        category CDATA #REQUIRED>

<!--  Overview of component's purpose  -->
<!ELEMENT overview (authors, summary, description, examplesr)>

<!-- Brief (1 or 2 sentence) summary. -->
<!ELEMENT summary (#PCDATA)>

<!--  Author(s) -->
<!ELEMENT authors (author+)>

<!--  1 author  -->
<!ELEMENT author (#PCDATA)>

<!-- Name of sr file which demonstrates use of this component  -->
<!ELEMENT examplesr %filename;>

<!-- All the extra code files needed to build this component -->
<!ELEMENT implementation (ccfile | cfile | ffile)+>

<!-- The name of a single .cc file -->
<!ELEMENT ccfile (#PCDATA)>

<!-- The name of a single .c file -->
<!ELEMENT cfile (#PCDATA)>

<!-- The name of a single .f file -->
<!ELEMENT ffile (#PCDATA)>

<!-- Component's inputs and outputs  -->
<!ELEMENT io (inputs, outputs)>

<!-- Component's inputs.  Inputs may come from a file, port, or device.  -->
<!ELEMENT inputs (file | port | device)+>
<!ATTLIST inputs lastportdynamic (yes | no) "no">

<!-- Component's outputs.  Outputs may be sent to a file, port, or device. -->
<!ELEMENT outputs (file | port | device)+>

<!-- Describe content of file (i.e. temperature data) and the datatype
     contained in the file. --> 
<!ELEMENT file (description, datatype)>

<!-- Describe data on port (i.e. temperature data) and the datatype being
     transmitted.  --> 
<!ELEMENT port (name, description, datatype, componentname+)>

<!-- The user-defined name for this port -->
<!ELEMENT name (#PCDATA)>

<!-- Describe data on device -->
<!ELEMENT device (devicename, description)>

<!-- GUI description (words and pictures) -->
<!ELEMENT gui (description, parameter+, img)>

<!-- Description of 1 gui parameter. -->
<!ELEMENT parameter (widget, label, description)>

<!-- Name of gui item (tcl/tk) widget -->
<!ELEMENT widget (#PCDATA)>

<!-- Gui item label -->
<!ELEMENT label (#PCDATA)>

<!--  Name of an image file -->
<!ELEMENT img %filename;>

<!-- Specify testing plan(s) -->
<!ELEMENT testing (plan+)>

<!-- Specify 1 testing plan.  -->
<!ELEMENT plan (description, step+)>

<!-- Specify 1 testing step -->
<!ELEMENT  step %DescFlow;>

<!-- Mini-documentation environment -->
<!ELEMENT description %DescFlow;>

<!-- Description information targeted at developers -->
<!ELEMENT developer %DevFlow;>

<!-- Calls attention to some piece of information. -->
<!ELEMENT note %AdmonFlow;>

<!-- A friendly word of advice. --> 
<!ELEMENT tip %AdmonFlow;>

<!-- A warning of some sort. -->
<!ELEMENT warning %AdmonFlow;>

<!-- Paragraph. -->
<!ELEMENT p %Inline;>

<!-- Relative link (relative to location of spec.xml file). -->
<!ELEMENT rlink %link.content;>
<!ATTLIST rlink %rlink.attr;>

<!-- Sci web site relative link -->
<!ELEMENT slink %link.content;>
<!ATTLIST slink %rlink.attr;>

<!-- "Phrases" - Content-based style tags. Inline stuff. -->
<!ELEMENT term %phrase.content;>        <!-- Introduce a new term -->
<!ELEMENT keyword %phrase.content;>     <!-- Introduce a keyword -->
<!ELEMENT keyboard %phrase.content;>    <!-- Show something typed at a keyboard -->
<!ELEMENT cite %phrase.content;>        <!-- Citation -->
<!ELEMENT acronym %phrase.content;>     <!-- An acronym -->             

<!-- Ordered list, unordered list, and description list. -->
<!ELEMENT orderedlist (listitem)+>
<!ELEMENT unorderedlist (listitem)+>
<!ELEMENT listitem %BasicFlow;>
<!ELEMENT desclist (desclistitem)+>
<!ELEMENT desclistitem (desclistterm, desclistdef)>
<!ELEMENT desclistterm (#PCDATA)>
<!ELEMENT desclistdef %BasicFlow;>

=== Uintah/Uintah/kokkos_dev/migrate_babelsidl/src/Packages/ModelCreation/Dataflow/XML/MatrixToString.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<component name="MatrixToString" category="Converter" optional="false">
  <overview>
    <authors>
      <author>Jeroen Stinstra</author>
    </authors>
    <summary>
      MatrixToString prints the contents of a matrix into a string.
    </summary>
    <description>
      <p>       
      MatrixToString prints the contents of a matrix into a string.
      For a dense matrix it outputs all the rows and columns of the
      matrix. For a sparse matrix only the non zero elements are
      printed.
      </p>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Matrix</name>
        <datatype>SCIRun::Matrix</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>String</name>
        <datatype>SCIRun::String</datatype>
      </port>
    </outputs>
  </io>
</component>

=== Uintah/Uintah/kokkos_dev/v2_0_0/src/Dataflow/XML/FieldReader.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "component.dtd">
<?xml-stylesheet href="component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="FieldReader" category="DataIO">
  <overview>
    <authors>
      <author>Alexei Samsonov</author>
    </authors>
    <summary>FieldReader allows the user to load-in any of the SCIRun supported Field types and then sends that Field to another module.</summary>
    <description><p>Upon opening, the The FieldReader GUI defaults to the directory that the user sets for their SCIRUN_DATA environment variable.  Otherwise, the GUI will default to the directory where the user's SCIRun executable resides. The current directory defaults to only show files with an .fld extension which helps the user determine the difference between Fields and other files.  However, the FieldReader can read-in a file with any extension so long as the data has the correct format.  If the user attempts to read-in a file that is other than a SCIRun supported Field, or uses an incorrect file format, an error message appears in the Error frame within the SCIRun enrvironment. Clicking the OK button will load the file and dismiss the GUI.</p>  
    </description>   
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <!-- one of (device port file) -->
    </inputs>
    <outputs>
      <port>
	<name>Output Data</name>
	
	<datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
  <gui>
    <img>../Modules/DataIO/doc/OpenFileUI.jpg</img>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/v1_10_0/src/Dataflow/XML/ClipField.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/Utilities/XML/component.dtd">
<?xml-stylesheet href="../../../doc/Utilities/XML/component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="ClipField" category="Fields">
  <overview>
    <authors>
      <author>Michael Callahan</author>
    </authors>
    <summary>Select a subset of a field.</summary>
    <description>
      <p>
        This module clips out a subset of a field.  The new field
        contains just the selected portion of the input field.
      </p>
      <p>

        The module runs in one of three different modes.  If a field
	is connected to the "Clip Field" port, the module will clip
	the input field such that only those elements inside of the
	clip field are preserved.  If Functional Clipping is turned
	on, then the function specified in the GUI is used to
	determine which elements are inside of the field.  Finally, if
	no Clip Field is connected and functional clipping is turned
	off then the GUI widget is used to select which portion of the
	input field to preserve.
      </p>
      <p>
        The type of the field is preserved in the clip, as well as the
        data values if possible.  Some field types are structured and
        thus not clippable.  This includes the LatVolField, ImageField,
        and Scanline field types.  There is an Unstructure module that
        can be used to convert these fields to appropriately
        unstructured versions before clipping.
      </p>
      <p>

        The function specified by the functional clipping mode is
	evaluated as a TCL expression.  $x is the variable used for
	the value in the field.  For example, "$x == 0 || $x == 1"
	will select all of the elements where the data value is equal
	to 0 or 1.
      </p>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
	<name>Input Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
      <port>
	<name>Clip Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
	<name>Selection Widget</name>
	<datatype>SCIRun::Geometry</datatype>
      </port>
      <port>
	<name>Output Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/SIGGRAPH02/src/Dataflow/XML/ColorMapWriter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/Utilities/XML/component.dtd">
<?xml-stylesheet href="../../../doc/Utilities/XML/component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="ColorMapWriter" category="DataIO">
  <overview>
    <authors>
      <author>Steven G. Parker</author>
    </authors>
    <summary>Save persistent representation of a colormap to a file.
    </summary>
    <description><p>Upon opening, the ColorMapWriter GUI defaults to the directory that the user sets for their SCIRUN_DATA environment variable.   Otherwise, the GUI will default to the directory where the user's SCIRun executable resides. The user can enter the name of a file that the matrix saves to. The file should have a .cmap extension. The default file name is MyColorMap.  The user may choose to save the file in either Binary or ASCII file format.</p>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
	<name>Input Data</name>
	<datatype>SCIRun::ColorMap</datatype>
      </port>
    </inputs>
  </io>
  <gui>
    <img>../Modules/DataIO/doc/SaveFileUI.jpg</img>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/v1_24_0/src/Dataflow/XML/LinearAlgebra.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "component.dtd">
<?xml-stylesheet href="component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   License for the specific language governing rights and limitations under
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->



<component name="LinearAlgebra" category="Math">
  <overview>
    <authors>
      <author>Michael Callahan</author>
    </authors>
    <summary>Do some linear algebra on input matrices.</summary>
    <description>

      <p>The LinearAlgebra module allows the user to input C++ code
      linear algebra expressions and then have them dynamically
      compiled and executed.</p>

      <p>The input variables are all of MatrixHandle type and are
      represented by the variables i1, i2, i3, i4, and i5 correlating
      with which input ports they are connected to.  The output
      variables are MatrixHandle references and are labeled o1, o2,
      o3, o4, and o5.</p>

      <p>The supported matrix operations can be found in
      src/Core/Datatypes/MatrixOperations.h, and are basically
      addition and multiplication.</p>

      <p>For example, the default "o1 = i1 * i2;" function would multiply
      the first two input matrices and put the result on the first
      output port.  "o2 = i1 * 3;" would multiply all of the values in
      the first input port and put the resulting matrix on the second
      output port.  If you used both lines it would do both.</p>

      <p>The various SCIRun Matrix headers are also included in addition
      to MatrixOperations.h.  So for example
      "o1 = scinew DenseMatrix(10, 20);" could be used to return a
      blank 10x20 dense matrix on the first output port.  It is also
      possible to write loops over the various matrix elements, etc.</p>

    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>i1</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>i2</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>i3</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>i4</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>i5</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>o1</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>o2</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>o3</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>o4</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>o5</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
    </outputs>
  </io>
  <gui>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/sr2_release_v0.1.1/src/Dataflow/XML/BundleGetPath.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "component.dtd">

<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   License for the specific language governing rights and limitations under
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->

<component name="BundleGetPath" category="Bundle">
  <overview>
    <authors>
      <author>Jeroen Stinstra</author>
    </authors>
    <summary>
      This module retrieves a 'path' object from a bundle. 
    </summary>
    <description>
      <p>This module retrieves a 'path' object from a bundle by
specifying the name of that object. The module has three output ports
that each can be programmed to retrieve a specific 'path' object. </p>
      
      <p>The module's first bundle output port just generates a copy
of the input bundle.</p>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>bundle</name>
        <datatype>SCIRun::Bundle</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>bundle</name>
        <datatype>SCIRun::Bundle</datatype>
      </port>
      <port>
        <name>path1</name>
        <datatype>SCIRun::Path</datatype>
      </port>
      <port>
        <name>path2</name>
        <datatype>SCIRun::Path</datatype>
      </port>
      <port>
        <name>path3</name>
        <datatype>SCIRun::Path</datatype>
      </port>
    </outputs>
  </io>
</component>

=== Uintah/Uintah/kokkos_dev/v1_8_0/src/Dataflow/XML/ChangeFieldDataAt.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/Utilities/XML/component.dtd">
<?xml-stylesheet href="../../../doc/Utilities/XML/component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
 
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
 
  The Original Source Code is SCIRun, released March 12, 2001.
 
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994
  University of Utah. All Rights Reserved.
-->

<component name="ChangeFieldDataAt" category="Fields">
  <overview>
    <authors>
      <author>McKay Davis</author>
    </authors>
    <summary>
      <p>
      </p>
    </summary>
    <description>
    </description>
  </overview>
  <implementation>
  </implementation>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Input Field</name>
        <datatype>SCIRun::Field</datatype>
	<description>
          <p>
            The field to be edited.
          </p>
        </description>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>Output Field</name>
        <datatype>SCIRun::Field</datatype>
        <description>
          <p>
            The edited field.
          </p>
        </description>
      </port>
    </outputs>
  </io>
  <gui>
    <description>
    </description>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/gui-branch/src/Dataflow/XML/Isosurface.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/component.dtd">
<?xml-stylesheet href="../../../doc/component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="Isosurface" category="Visualization">
  <overview>
    <authors>
      <author>Yarden Livnat</author>
    </authors>
    <summary>Isosurface allows visualization of an isopotential
     surface within a model.
     </summary>
     <description>
      <p>Changing the Iso Value allows visualization of any
      isopotential surface.</p>
      <p>Method Marching Cubes (MC) looks at the isopotential at the
      corners of every cell.  You can specify the number of processor
      (np).</p>
      <p>Noise method stores the min and max of all cells into a
      table.
      </p>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
      <port>
        <name>Color Map</name>
	<datatype>SCIRun::ColorMap</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>Surface</name>
	<datatype>SCIRun::Field</datatype>
      </port>
      <port>
        <name>Geometry</name>
	<datatype>SCIRun::Geometry</datatype>
      </port>
    </outputs>
  </io>
  <gui>
    <img>../Modules/Visualization/doc/IsoSurfaceUI.jpg</img>
  </gui>
  <testing>
  </testing>
</component>
