=== Uintah/Uintah/kokkos_dev/FIELD_REDESIGN/doc/ReferenceGuide/component.dtd
<!--
        
Component  specification dtd.

-->

<!-- ********** Parameter Entities ********** -->

<!ENTITY % filename "(#PCDATA)">

<!-- A relative path specification. Used by rlink and slink elements'
     attributes. --> 
<!ENTITY % rpath "CDATA">

<!-- Link stuff -->
<!ENTITY % links "rlink | slink">
<!ENTITY % rlink.attr "path %rpath; #REQUIRED">

<!-- Text level stuff -->
<!ENTITY % phrase "term | keyword | keyboard | cite | acronym">
<!ENTITY % phrase.content "(#PCDATA)">
<!ENTITY % inline "%phrase; | %links;">
<!ENTITY % Inline "(#PCDATA | %inline;)*">
<!ENTITY % link.content "(#PCDATA | %phrase;)*">

<!-- Higher level stuff -->
<!ENTITY % lists "orderedlist | unorderedlist | desclist">
<!ENTITY % admonition "note | tip | warning">
<!ENTITY % block "p">
<!ENTITY % flow "%block; | %lists;">
<!ENTITY % BasicFlow "(%flow;)*">
<!ENTITY % DescFlow "(%flow; | developer | %admonition;)*">
<!ENTITY % DevFlow "(%flow; | %admonition;)*">
<!ENTITY % AdmonFlow "(%flow;)*">

<!-- ********** Elements ********** -->

<!-- A couple of reusable elements  -->
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT componentname (#PCDATA)>
<!ELEMENT devicename (#PCDATA)>

<!-- Top level -->
<!ELEMENT component (overview, implementation?, io, gui?, testing)>
<!ATTLIST component 
        name CDATA #REQUIRED
        category CDATA #REQUIRED>

<!--  Overview of component's purpose  -->
<!ELEMENT overview (authors, summary, description, examplesr)>

<!-- Brief (1 or 2 sentence) summary. -->
<!ELEMENT summary (#PCDATA)>

<!--  Author(s) -->
<!ELEMENT authors (author+)>

<!--  1 author  -->
<!ELEMENT author (#PCDATA)>

<!-- Name of sr file which demonstrates use of this component  -->
<!ELEMENT examplesr %filename;>

<!-- All the extra code files needed to build this component -->
<!ELEMENT implementation (ccfile | cfile | ffile)+>

<!-- The name of a single .cc file -->
<!ELEMENT ccfile (#PCDATA)>

<!-- The name of a single .c file -->
<!ELEMENT cfile (#PCDATA)>

<!-- The name of a single .f file -->
<!ELEMENT ffile (#PCDATA)>

<!-- Component's inputs and outputs  -->
<!ELEMENT io (inputs, outputs)>

<!-- Component's inputs.  Inputs may come from a file, port, or device.  -->
<!ELEMENT inputs (file | port | device)+>
<!ATTLIST inputs lastportdynamic (yes | no) "no">

<!-- Component's outputs.  Outputs may be sent to a file, port, or device. -->
<!ELEMENT outputs (file | port | device)+>

<!-- Describe content of file (i.e. temperature data) and the datatype
     contained in the file. --> 
<!ELEMENT file (description, datatype)>

<!-- Describe data on port (i.e. temperature data) and the datatype being
     transmitted.  --> 
<!ELEMENT port (name, description, datatype, componentname+)>

<!-- The user-defined name for this port -->
<!ELEMENT name (#PCDATA)>

<!-- Describe data on device -->
<!ELEMENT device (devicename, description)>

<!-- GUI description (words and pictures) -->
<!ELEMENT gui (description, parameter+, img)>

<!-- Description of 1 gui parameter. -->
<!ELEMENT parameter (widget, label, description)>

<!-- Name of gui item (tcl/tk) widget -->
<!ELEMENT widget (#PCDATA)>

<!-- Gui item label -->
<!ELEMENT label (#PCDATA)>

<!--  Name of an image file -->
<!ELEMENT img %filename;>

<!-- Specify testing plan(s) -->
<!ELEMENT testing (plan+)>

<!-- Specify 1 testing plan.  -->
<!ELEMENT plan (description, step+)>

<!-- Specify 1 testing step -->
<!ELEMENT  step %DescFlow;>

<!-- Mini-documentation environment -->
<!ELEMENT description %DescFlow;>

<!-- Description information targeted at developers -->
<!ELEMENT developer %DevFlow;>

<!-- Calls attention to some piece of information. -->
<!ELEMENT note %AdmonFlow;>

<!-- A friendly word of advice. --> 
<!ELEMENT tip %AdmonFlow;>

<!-- A warning of some sort. -->
<!ELEMENT warning %AdmonFlow;>

<!-- Paragraph. -->
<!ELEMENT p %Inline;>

<!-- Relative link (relative to location of spec.xml file). -->
<!ELEMENT rlink %link.content;>
<!ATTLIST rlink %rlink.attr;>

<!-- Sci web site relative link -->
<!ELEMENT slink %link.content;>
<!ATTLIST slink %rlink.attr;>

<!-- "Phrases" - Content-based style tags. Inline stuff. -->
<!ELEMENT term %phrase.content;>        <!-- Introduce a new term -->
<!ELEMENT keyword %phrase.content;>     <!-- Introduce a keyword -->
<!ELEMENT keyboard %phrase.content;>    <!-- Show something typed at a keyboard -->
<!ELEMENT cite %phrase.content;>        <!-- Citation -->
<!ELEMENT acronym %phrase.content;>     <!-- An acronym -->             

<!-- Ordered list, unordered list, and description list. -->
<!ELEMENT orderedlist (listitem)+>
<!ELEMENT unorderedlist (listitem)+>
<!ELEMENT listitem %BasicFlow;>
<!ELEMENT desclist (desclistitem)+>
<!ELEMENT desclistitem (desclistterm, desclistdef)>
<!ELEMENT desclistterm (#PCDATA)>
<!ELEMENT desclistdef %BasicFlow;>

=== Uintah/Uintah/kokkos_dev/v1_4_0/src/Dataflow/XML/ColorMapReader.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/component.dtd">
<?xml-stylesheet href="../../../doc/component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="ColorMapReader" category="DataIO">
  <overview>
    <authors>
      <author>Steven G. Parker</author>
    </authors>
    <summary>Read a persistent colormap from a file.</summary>
    <description>
    </description>
  </overview>
  <io>
    <outputs>
      <port>
	<name>Output Data</name>
	<datatype>SCIRun::ColorMap</datatype>
      </port>
    </outputs>
  </io>
  <gui>
    <img>../Modules/DataIO/doc/OpenFileUI.jpg</img>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/v2_0_0/src/Packages/BioPSE/Dataflow/XML/DipoleMatrixSourceRHSQuadratic.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<?xml-stylesheet href="../../../../../doc/package-component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<component name="DipoleMatrixSourceRHSQuadratic" category="Forward">
  <overview>
    <authors>
    </authors>
  </overview>
  <implementation>
  </implementation>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>QuadTetVolField</name>
        <datatype>SCIRun::Field</datatype>
      </port>
      <port>
        <name>DipoleSource</name>
        <datatype>SCIRun::Field</datatype>
      </port>
      <port>
        <name>Input RHS</name>
        <datatype>SCIRun::Matrix</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>OutPut RHS</name>
        <datatype>SCIRun::Matrix</datatype>
      </port>
    </outputs>
  </io>
  <gui>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/v1_22_0/src/Packages/BioPSE/Dataflow/XML/SetupFEMatrix.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">

<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   License for the specific language governing rights and limitations under
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->



<component name="SetupFEMatrix" category="Forward">
  <overview>
    <authors>
      <author>Alexei Samsonov</author>
      <author>Ruth Nicholson Klepfer</author>
    </authors>
    
    <summary>The module sets up a mesh with conductivity tensors and
      Dirichlet boundary conditions specifically for bioelectric field
      problems.
    </summary>
    
    <description>
      <p>Version Date: March 2001</p><p>Version: 1.0</p>

      <p>The module provides basic means for construction of the FE
      matrix with linear elements for bioelectric field problems
      (discretization of Poisson equation for volume conductor
      problem). The input field should have properties with lookup
      names that correspondend to the bioelectric field problem. The
      module conventions appear below:</p>
      
      <orderedlist>
	<listitem>
	  <p>The Field containing a mesh should be a TetVolField(char) type,
	  which contains indices to the property 'table'; actual values of the 
	  conductivity tensors, optimizing
	  storage.</p>
	</listitem>
	<listitem>
	  <p>The property of the conductivity mesh name 'table' should
	  have the associated data object Array1(Tensor) type. Any
	  lookup into the table is done by dereferencing indices of
	  conductivity mesh, the module performs any lookup into the table.</p>
	</listitem>
	<listitem>
	  <p>Dirichlet boundary conditions, if any, should be
	  represented as a property with the name "dirichlet" and be
	  of a vector(pair(int, double)) type, where "int" field
	  corresponds to node index, and "double" field is the value
	  of potential at the node.</p>
	</listitem>
      </orderedlist>
      
      <note>
	<p>BioPSE::Algorithm::BuildFEMatrix::build_FEMatrix() performs
	the actual computation of the matrix. Other modules or any
	other code may use the algorithm for other kinds of problems
	involving discretization of the Poisson equation in 3D by
	linear finite elements.</p>
      </note>
      
      <developer>
	<p>The discretization of the Poisson equation on the supplied
	mesh is performed by linear finite elements using Galerkin
	approach.</p>
      </developer>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <!-- one of (device port file) -->
      <port>
	<name>Mesh</name>
	<description>
	  <p>Takes a handle to Field object containing properties
	  described in overview section</p>
	</description>
	<datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <!-- one of (device port file) -->
      <port>
	<name>Stiffness Matrix</name>
	<description>
	  <p>Sends a handle to the sparse matrix obtained from
	  discretization of the problem by finite elements</p>
	  <note>
	    <p>The handle is to base class of SparseRowMatrix, namely,
	    Matrix</p>
	  </note>
	</description>
	<datatype>SCIRun::Matrix</datatype>
      </port>
    </outputs>
  </io>
  <gui>
    <description>
      <p>The SetupFEMatrix GUI contains three elements.  </p>
    </description>
    <parameter>
      <widget>Entry</widget>
      <datatype>Integer</datatype>
      <label>Number of Threads</label>
      <description>
	<p></p>
      </description>
    </parameter>
    <parameter>
      <widget>Check Button</widget>
      <datatype>N/A</datatype>
      <label>Use Conductivities</label>
      <description>
	<p>
          The "Use Conductivities" box tells the module to look up the
          conductivity for each element and to use that information
          when constructing the stiffness matrices.  If it is not
          checked, the module will use the identity matrix for each
          element instead (i.e. what was div(sigma x grad(phi)) turns
          into div(grad(phi))).  This is useful for demonstrating the
          effects of volumetric inhomogeneities on the electric field.
          And in practice, it's also a useful debugging tools -- you
          can immediately see if a solution that isn't converging or
          is giving strange results is getting screwed up because of
          bad conductivity values or because of something else
          (e.g. something is wrong with the mesh).
        </p>
      </description>
    </parameter>
    <parameter>
      <widget>Check Button</widget>
      <datatype>N/A</datatype>
      <label>Use Conductivity Basis Matrices</label>
      <description>
	<p>
          The "Use Conductivity Basis Matrices" is just an efficiency
          option for the case where the user wants to experiment with
          varying the conductivity for some of the materials.  Note:
          it only works with isotropic materials, and when we have an
          indexed table of Tensors (i.e. a Field&lt;int> with a
          conductivity_table Property, rather than a Field&lt;Tensor>
          where each element has a unique Tensor).  This option will
          precompute a decomposition of A into:

          A = sigma_1 x A'_1 + sigma_2 x A'_2 + ... sigma_N x A'_N 

          where the A'_n matrices are the same size and structure (in
          the sparse matrix sense) as A, but just contain
          contributions from elements of material type n.  The sigma_n
          values are just the isotropic conductivities of the
          different materials.  If this box is checked, we build this
          decomposition.  Then, when a new Field comes in, the module
          will check to make sure that only the conductivity_table has
          changed, and will regenerate A by adding together weighted
          contributions from the basis matrices, A'_n.  In practice
          this approach is extremely useful for the parameterized
          conductivity search application that's implement in
          Packages/BioPSE/nets/conductivity-search.net
        </p>
      </description>
    </parameter>
  </gui>
</component>

=== Uintah/Uintah/kokkos_dev/FIELD_REDESIGN/src/Packages/Uintah/Dataflow/XML/NodeHedgehog.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/ReferenceGuide/component.dtd">

<component name="NodeHedgehog" category="Visualization">
  <overview>
    <authors>
      <author>Steven G. Parker</author>
      <author>James Bigler</author>
    </authors>
    <summary>Summary not available yet.</summary>
    <description>
      <p>Version Date: June 2000</p><p>Version: 2.0</p>
    </description>
  </overview>
  <io>
  </io>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/v1_8_0/src/Packages/Fusion/Dataflow/XML/MDSPlusFieldReader.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../../doc/Utilities/XML/component.dtd">
<?xml-stylesheet href="../../../../../doc/Utilities/XML/package-component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<component name="MDSPlusFieldReader" category="DataIO">
  <overview>
    <authors>
      <author>ARSanderson</author>
    </authors>
  </overview>
  <implementation>
  </implementation>
  <io>
    <inputs lastportdynamic="no">
    </inputs>
    <outputs>
      <port>
	<name>Output Pressure Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
      <port>
	<name>Output B Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
      <port>
	<name>Output V Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
      <port>
	<name>Output J Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
  <gui>
    <parameter>
      <widget>Label</widget>
      <label>Autogenerated GUI explanation</label>
    </parameter>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/v1_4_0/src/Packages/RobV/Dataflow/XML/TetVol2QuadraticTetVol.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../../doc/component.dtd">
<?xml-stylesheet href="../../../../../doc/package-component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<component name="TetVol2QuadraticTetVol" category="Quadratic">
  <overview>
    <authors>
    </authors>
  </overview>
  <implementation>
  </implementation>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>InputTetField</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>OutputQuadraticTet</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
  <gui>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/v1_10_0/src/Packages/Wangxl/Dataflow/XML/SurfaceRecon.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../../doc/Utilities/XML/component.dtd">
<?xml-stylesheet href="../../../../../doc/Utilities/XML/package-component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<component name="SurfaceRecon" category="Surface">
  <overview>
    <authors>
    </authors>
  </overview>
  <implementation>
  </implementation>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>point_cloud</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>surface_mesh</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
  <gui>
    <parameter>
      <widget>Label</widget>
      <label>Autogenerated GUI explanation</label>
    </parameter>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/teem_tuple_removed/src/Dataflow/XML/Centroids.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "component.dtd">
<?xml-stylesheet href="component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="Centroids" category="FieldsCreate">
  <overview>
    <authors>
      <author>Michael Callahan</author>
    </authors>
    <summary>Computes a PointCloudField containing all of the element
  centers for a field.</summary>
    <description>
      The Centriods module computes a PointCloudField containing all
      of the element centers for a field.  For instance, if the input
      field is a TetVolField then the output field would contain the
      center of each tetrahedra.  An input PointCloudField would return
      the same data locations.

      The output field is always a PointCloudField of doubles, and
      contains no data.  If data is needed at the points then an
      interpolation module should be used to recover them.
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
	<name>TetVolField</name>
	<datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
	<name>PointCloudField</name>
	<datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
  <testing>
  </testing>
</component>
