=== Uintah/Uintah/kokkos_dev/FIELD_REDESIGN/doc/ReferenceGuide/component.dtd
<!--
        
Component  specification dtd.

-->

<!-- ********** Parameter Entities ********** -->

<!ENTITY % filename "(#PCDATA)">

<!-- A relative path specification. Used by rlink and slink elements'
     attributes. --> 
<!ENTITY % rpath "CDATA">

<!-- Link stuff -->
<!ENTITY % links "rlink | slink">
<!ENTITY % rlink.attr "path %rpath; #REQUIRED">

<!-- Text level stuff -->
<!ENTITY % phrase "term | keyword | keyboard | cite | acronym">
<!ENTITY % phrase.content "(#PCDATA)">
<!ENTITY % inline "%phrase; | %links;">
<!ENTITY % Inline "(#PCDATA | %inline;)*">
<!ENTITY % link.content "(#PCDATA | %phrase;)*">

<!-- Higher level stuff -->
<!ENTITY % lists "orderedlist | unorderedlist | desclist">
<!ENTITY % admonition "note | tip | warning">
<!ENTITY % block "p">
<!ENTITY % flow "%block; | %lists;">
<!ENTITY % BasicFlow "(%flow;)*">
<!ENTITY % DescFlow "(%flow; | developer | %admonition;)*">
<!ENTITY % DevFlow "(%flow; | %admonition;)*">
<!ENTITY % AdmonFlow "(%flow;)*">

<!-- ********** Elements ********** -->

<!-- A couple of reusable elements  -->
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT componentname (#PCDATA)>
<!ELEMENT devicename (#PCDATA)>

<!-- Top level -->
<!ELEMENT component (overview, implementation?, io, gui?, testing)>
<!ATTLIST component 
        name CDATA #REQUIRED
        category CDATA #REQUIRED>

<!--  Overview of component's purpose  -->
<!ELEMENT overview (authors, summary, description, examplesr)>

<!-- Brief (1 or 2 sentence) summary. -->
<!ELEMENT summary (#PCDATA)>

<!--  Author(s) -->
<!ELEMENT authors (author+)>

<!--  1 author  -->
<!ELEMENT author (#PCDATA)>

<!-- Name of sr file which demonstrates use of this component  -->
<!ELEMENT examplesr %filename;>

<!-- All the extra code files needed to build this component -->
<!ELEMENT implementation (ccfile | cfile | ffile)+>

<!-- The name of a single .cc file -->
<!ELEMENT ccfile (#PCDATA)>

<!-- The name of a single .c file -->
<!ELEMENT cfile (#PCDATA)>

<!-- The name of a single .f file -->
<!ELEMENT ffile (#PCDATA)>

<!-- Component's inputs and outputs  -->
<!ELEMENT io (inputs, outputs)>

<!-- Component's inputs.  Inputs may come from a file, port, or device.  -->
<!ELEMENT inputs (file | port | device)+>
<!ATTLIST inputs lastportdynamic (yes | no) "no">

<!-- Component's outputs.  Outputs may be sent to a file, port, or device. -->
<!ELEMENT outputs (file | port | device)+>

<!-- Describe content of file (i.e. temperature data) and the datatype
     contained in the file. --> 
<!ELEMENT file (description, datatype)>

<!-- Describe data on port (i.e. temperature data) and the datatype being
     transmitted.  --> 
<!ELEMENT port (name, description, datatype, componentname+)>

<!-- The user-defined name for this port -->
<!ELEMENT name (#PCDATA)>

<!-- Describe data on device -->
<!ELEMENT device (devicename, description)>

<!-- GUI description (words and pictures) -->
<!ELEMENT gui (description, parameter+, img)>

<!-- Description of 1 gui parameter. -->
<!ELEMENT parameter (widget, label, description)>

<!-- Name of gui item (tcl/tk) widget -->
<!ELEMENT widget (#PCDATA)>

<!-- Gui item label -->
<!ELEMENT label (#PCDATA)>

<!--  Name of an image file -->
<!ELEMENT img %filename;>

<!-- Specify testing plan(s) -->
<!ELEMENT testing (plan+)>

<!-- Specify 1 testing plan.  -->
<!ELEMENT plan (description, step+)>

<!-- Specify 1 testing step -->
<!ELEMENT  step %DescFlow;>

<!-- Mini-documentation environment -->
<!ELEMENT description %DescFlow;>

<!-- Description information targeted at developers -->
<!ELEMENT developer %DevFlow;>

<!-- Calls attention to some piece of information. -->
<!ELEMENT note %AdmonFlow;>

<!-- A friendly word of advice. --> 
<!ELEMENT tip %AdmonFlow;>

<!-- A warning of some sort. -->
<!ELEMENT warning %AdmonFlow;>

<!-- Paragraph. -->
<!ELEMENT p %Inline;>

<!-- Relative link (relative to location of spec.xml file). -->
<!ELEMENT rlink %link.content;>
<!ATTLIST rlink %rlink.attr;>

<!-- Sci web site relative link -->
<!ELEMENT slink %link.content;>
<!ATTLIST slink %rlink.attr;>

<!-- "Phrases" - Content-based style tags. Inline stuff. -->
<!ELEMENT term %phrase.content;>        <!-- Introduce a new term -->
<!ELEMENT keyword %phrase.content;>     <!-- Introduce a keyword -->
<!ELEMENT keyboard %phrase.content;>    <!-- Show something typed at a keyboard -->
<!ELEMENT cite %phrase.content;>        <!-- Citation -->
<!ELEMENT acronym %phrase.content;>     <!-- An acronym -->             

<!-- Ordered list, unordered list, and description list. -->
<!ELEMENT orderedlist (listitem)+>
<!ELEMENT unorderedlist (listitem)+>
<!ELEMENT listitem %BasicFlow;>
<!ELEMENT desclist (desclistitem)+>
<!ELEMENT desclistitem (desclistterm, desclistdef)>
<!ELEMENT desclistterm (#PCDATA)>
<!ELEMENT desclistdef %BasicFlow;>

=== Uintah/Uintah/kokkos_dev/v2_0_0/src/Dataflow/XML/MatrixReader.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "component.dtd">
<?xml-stylesheet href="component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="MatrixReader" category="DataIO">
  <overview>
    <authors>
      <author>Steven G. Parker</author>
    </authors>
    <summary>The MatrixReader moudle reads a persistent matrix from a file and sends that matrix to another module.</summary>
    <description><p>Upon opening, the The MatrixReader GUI defaults to the directory that the user sets for their SCIRUN_DATA environment variable.  Otherwise, the GUI will default to the directory where the user's SCIRun executable resides. The current directory defaults to only show files with an .mat extension which helps the user determine the difference between matrix files and other files.  However, the MatrixReader can read-in a file with any extension so long as the data has the correct format.  If the user attempts to read-in a file that is other than a SCIRun supported Matrix, or uses an incorrect file format, an error message appears in the Error frame within the SCIRun enrvironment. Clicking the OK button will load the file and dismiss the GUI.</p>
    </description>
  </overview>
  <io>
    <outputs>
      <port>
	<name>Output Data</name>
	<datatype>SCIRun::Matrix</datatype>
      </port>
    </outputs>
  </io>
  <gui>
    <img>../Modules/DataIO/doc/OpenFileUI.jpg</img>
  </gui>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/osx_tiger/src/Packages/Teem/Dataflow/XML/NrrdReader.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">

<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   License for the specific language governing rights and limitations under
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->



<component name="NrrdReader" category="DataIO">
  <overview>
    <authors>
      <author>David Weinstein</author>
      <author>Martin Cole</author>
    </authors>
    <summary>Open a raw nrrd or a SCIRun wrapped nrrd.</summary>
    <description>

    <p>Interface to introdude a NrrdData into the net. NrrdReader can
    open a raw nrrd, or a previously saved SCIRun wrapped nrrd
    (NrrdData). If the first axis is vector or tensor data, make sure
    that the nrrdKind for that axis is set appropriately.  This can be
    checked via the <modref package="Teem" name="NrrdInfo"/> module
    and changed via the <modref package="Teem" name="UnuAxinfo"/>
    module.</p>

    </description>
    <examplesr>Teem/nets/test/io.net</examplesr>
  </overview>
  <io>
    <inputs lastportdynamic="no">
    </inputs>
    <outputs>
      <port>
        <name>Output Data</name>
	<datatype>SCIRun::Nrrd</datatype>
      </port>
    </outputs>
  </io>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/migrate_babelsidl/src/Packages/ModelCreation/Dataflow/XML/SplitFieldByConnectedRegion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<component name="SplitFieldByConnectedRegion" category="FieldsCreate" optional="false">
  <overview>
    <authors>
      <author>Jeroen Stinstra</author>
    </authors>
    <summary>
      This module splits a field into a series of fields in which every field
      contains a segment of the field that was not topologically connected to the
      other parts of the field. 
    </summary>
    <description>
      <p> 
      This module splits a field into a series of fields in which every field
      contains a segment of the field that was not topologically connected to the
      other parts of the field. Thos module can for example be used to split a
      surface separating different domains in a set of surfaces that are not
      topologically connected. The out of this module is a bundle with the set
      of fields.
      </p>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Field</name>
        <datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>Bundle</name>
        <datatype>SCIRun::Bundle</datatype>
      </port>
    </outputs>
  </io>
</component>

=== Uintah/Uintah/kokkos_dev/v1_4_0/src/Dataflow/XML/Unstructure.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/component.dtd">
<?xml-stylesheet href="../../../doc/component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="Unstructure" category="Fields">
  <overview>
    <authors>
      <author>Michael Callahan</author>
    </authors>
    <summary>
      Convert a structured field into an unstructured field for editing.
    </summary>
    <description>
      <p>
        This converts a LatVolField into a HexVolField, an ImageField into a
        QuadSurfField, or a ScanlineField into a CurveField.  The
        structured meshes are not editable, as that operation does not
        preserve structure.  Data values and locations are preserved
        in the transformation.
      </p>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
	<name>Input Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
	<name>Output Field</name>
	<datatype>SCIRun::Field</datatype>
      </port>
    </outputs>
  </io>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/migrate_babelsidl/src/Packages/Insight/Dataflow/XML/VectorConfidenceConnectedImageFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<!--
   For more information, please see: http://software.sci.utah.edu

   The MIT License

   Copyright (c) 2004 Scientific Computing and Imaging Institute,
   University of Utah.

   License for the specific language governing rights and limitations under
   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
-->

<!-- This is an automatically generated file for the
     itk::VectorConfidenceConnectedImageFilter
-->

<component name="VectorConfidenceConnectedImageFilter" category="Filters">
  <overview>
    <authors>
    <author>
    Automatically generated by SCIRun Code Generator
    </author>
</authors>
    <summary>
    </summary>
    <description>
<p>
This filter extracts a connected set of pixels whose pixel intensities are consistent with the pixel statistics of a seed point. The mean and variance across a neighborhood (8-connected, 26-connected, etc.) are calculated for a seed point. Then pixels connected to this seed point whose values are within the confidence interval for the seed point are grouped. The width of the confidence interval is controlled by the "Multiplier" variable (the confidence interval is the mean plus or minus the "Multiplier" times the standard deviation). If the intensity variations across a segment were gaussian, a "Multiplier" setting of 2.5 would define a confidence interval wide enough to capture 99% of samples in the segment.

After this initial segmentation is calculated, the mean and variance are re-calculated. All the pixels in the previous segmentation are used to calculate the mean the standard deviation (as opposed to using the pixels in the neighborhood of the seed point). The segmentation is then recalculted using these refined estimates for the mean and variance of the pixel values. This process is repeated for the specified number of iterations. Setting the "NumberOfIterations" to zero stops the algorithm after the initial segmentation from the seed point.

NOTE: the lower and upper threshold are restricted to lie within the valid numeric limits of the input data pixel type. Also, the limits may be adjusted to contain the seed point's intensity. 
  This module encapsulates the functionality of the ITK Filter itk::VectorConfidenceConnectedImageFilter.  See the <ulink url="http://www.itk.org">ITK web site</ulink> for detailed information on this filter.
  </p>
</description>
  </overview>
  
  <io>
    <inputs lastportdynamic="no">  
      <port>
        <name>InputImage</name>
        <datatype>Insight::ITKDatatype</datatype>
      </port>
    </inputs>
    <outputs>  
      <port>
        <name>OutputImge</name>
        <datatype>Insight::ITKDatatype</datatype>
      </port>
    </outputs>
  </io>
</component>

=== Uintah/Uintah/kokkos_dev/v1_8_0/src/Dataflow/XML/StreamLines.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/Utilities/XML/component.dtd">
<?xml-stylesheet href="../../../doc/Utilities/XML/component.xsl" type="text/xsl"?>
<?cocoon-process type="xslt"?>

<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->


<component name="StreamLines" category="Visualization">
  <overview>
    <authors>
      <author>Chris Moulding</author>
      <author>Michael Callahan</author>
    </authors>
    <summary>
      <p>
        The StreamLines module visualizes vector fields by generating
curves that interpolate the flow of vectors in a Field. 
      </p>
    </summary>
    <description>
      <p>
The StreamLines module visualizes vector fields by
generating curves that interpolate the flow of vectors in a Field.
      </p>

<p> The Flow Field input port is the vector field on which the path
intergration of the seed points will be performed.  This may be a
vector field with any volume geometry type.  Surfaces and lower order
fields do not currently work due to numerical error.  The second input
port, Seeds, contains the initial values for which the flow will be
computed.  This may be a field of any type, as just the node positions
are used.  Seeds which are not contained within the flow field are
just discarded.  The module requires use of both field inputs in order
to execute.</p>

<p> The StreamLines module has one output, Streamlines, a CurveMesh,
representing a collection of stream lines computed for the Flow field
given the set of initial seed points.</p>

<p> This module uses one of several similar numeric integration
methods.  They are taken directly from Numerical Analysis by David
Kincaid and Ward Cheney, c1991.  Adams-Bashforth is a Multi-Step
method that offers the fastest performance by reusing existing samples
when possible.  It presents some interesting artifacts on
discontinuous models such that it is easy to visualize where those
discontinuities take place.  Heun is a second order Runge-Kutta
solver, and is sufficient for most smoothly varying fields, such as
linearly interpolated gradient fields over volume elements.  Classic
4th Order Runge-Kutta is presented for reference and provides
excellent results in general.  Adaptive Runge-Kutta-Fehlberg is a 5/6
order solver which provides the best overall results at the cost of
more computation time.  It is also the only adaptive method, meaning
the step size of the algorithm is adjusted dynamically as the stream
moves through the flow field. </p>


<p> All of the computation methods are similar in that they take a
step, (based upon the Step Size indicated) examine the derivative at
that point, and then procede in that new direction.  Adaptive
Runge-Kutta-Fehlberg also determines if a stepsize correction is
necessary. This determination is based upon the Error Tolerance
value. </p>

<p> The StreamLines GUI includes text fields for Error Tolerance, Step
Size, and Maximum Steps. The Error Tolerance text field represents the
margin of error when doing an adaptive calculation of the stream
lines.  Maximum Steps represents the maximum number of iterations.
</p>

<p>The user can specify whether streamlines are computed in negative
and/or, positive directions by changing the Direction radio
buttons. The Color Style options are Constant and Increment, both of
which affect how values are attached to the output field.  By
selecting Constant, the output field will range from zero to the
number of seed points so that every stream line has exactly one
value. The Increment option changes the value of output field such
that they start at zero where the seed point are, and go up by one on
each step away in either direction. </p>

<p> The Filter Colinear Points check box is a postprocess on the
streams.  It passes over the streams and removes all points that are
too close together, as well as points that are colinear.  It is useful
for rendering the streamlines as it greatly simplifies them while
retaining their visual appearance.</p>
    </description>
  </overview>
  <implementation>
  </implementation>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Flow field</name>
        <description>
          <p>
            Flow field is the field to be visualized.  It can be 
     	    2D or 3D and can be structured or unstructured.
	    StreamLines is more effective if Flow field represents the
	    flow present in a field rather than the gradient of a generic
	    field. 
          </p>
        </description>
        <datatype>SCIRun::Field</datatype>
        <componentname>GenField</componentname>
        <componentname>ReadField</componentname>
      </port>
      <port>
        <name>Seeds</name>
        <description>
          <p>
            Seeds is a field whose nodes will be used as seed points, or
            starting points, for the generation of the stream lines.
          </p>
        </description>
        <datatype>SCIRun::Field</datatype>
        <componentname>GenField</componentname>
        <componentname>ReadField</componentname>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>Streamlines</name>
        <description>
          <p>
            Streamlines is a CurveMesh&lt;double&gt;
          </p>
        </description>
        <datatype>SCIRun::Field</datatype>
        <componentname>Render3D</componentname>
        <componentname>WriteGeometry</componentname>
      </port>
    </outputs>
  </io>
  <gui>
    <description>
      <p>
        The GUI for StreamLines allows the user to control the 
        parameters for the advection algorithm (Runge-Kutta-Fehlberg)
        used to extract the streamlines. 
      </p>
    </description>
    <img>../Modules/Visualization/doc/StreamLinesGUI.jpg</img>
    <parameter>
      <widget>Button</widget>
      <label>Execute</label>
      <description>
        <p>
          Sends a request to the scheduler to have this component
          executed.
        </p>
      </description>
    </parameter>
    <parameter>
      <widget>Entry</widget>
      <label>Error Tolerance</label>
      <description>
        <p>
          The value entered here will control the RKF step-size
          variable.  It will adaptively change the step-size based on
          how close the local truncation error is to this value.
        </p>
      </description>
    </parameter>
    <parameter>
      <widget>Entry</widget>
      <label>Step Size</label>
      <description>
        <p>
          The value entered here will provide RKF with the initial
          step size.
        </p>
      </description>
    </parameter>
    <parameter>
      <widget>Entry</widget>
      <label>Maximum Steps</label>
      <description>
        <p>
          The value entered here will be the maximum number of nodes
          allowed in a single stream line (to prevent infinite run
          time). 
        </p>
      </description>
    </parameter>
  </gui>
  <testing>
    <plan>
      <description>
        <p>
        </p>
      </description>
      <step>
        <p>
          nothing yet.
        </p>
      </step>
    </plan>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/FIELD_REDESIGN/src/Dataflow/XML/PathWriter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../../doc/ReferenceGuide/component.dtd">

<component name="PathWriter" category="Writers">
  <overview>
    <authors>
      <author>Dave Weinstein</author>
    </authors>
    <summary>Summary not available yet.</summary>
    <description>
      <p>Version Date: 1994</p><p>Version: 1.0</p>
    </description>
  </overview>
  <io>
  </io>
  <testing>
  </testing>
</component>

=== Uintah/Uintah/kokkos_dev/migrate_babelsidl/src/Packages/ModelCreation/Dataflow/XML/ResizeMatrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../../../../Dataflow/XML/component.dtd">
<component name="ResizeMatrix" category="Math" optional="false">
  <overview>
    <authors>
      <author>Jeroen Stinstra</author>
    </authors>
    <summary>
      This module resizes a matrix.

    </summary>
    <description>
      <p>        This module resizes a matrix. One can specify the new size of the matrix by connecting scalar values to the input or by setting the appropriate values in the GUI. </p>
    </description>
  </overview>
  <io>
    <inputs lastportdynamic="no">
      <port>
        <name>Matrix</name>
        <datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>M</name>
        <datatype>SCIRun::Matrix</datatype>
      </port>
      <port>
        <name>N</name>
        <datatype>SCIRun::Matrix</datatype>
      </port>
    </inputs>
    <outputs>
      <port>
        <name>Matrix</name>
        <datatype>SCIRun::Matrix</datatype>
      </port>
    </outputs>  
  </io>
</component>
